In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
X = iris.data
y = iris.target

In [3]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [4]:
import pandas as pd
pd.DataFrame(X, columns=iris.feature_names).head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [5]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [6]:
from sklearn.neighbors import KNeighborsClassifier

# instantiate the model (with the default parameters)
knn = KNeighborsClassifier()

# fit the model with data (occurs in-place)
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [7]:
knn.predict([[3, 5, 4, 2]])

array([1])

In [8]:
simple_train = ['call you tonight', 'Call me a cab', 'please call me... PLEASE!']

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

In [10]:

# learn the 'vocabulary' of the training data (occurs in-place)
vect.fit(simple_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [11]:

# examine the fitted vocabulary
vect.get_feature_names()

['cab', 'call', 'me', 'please', 'tonight', 'you']

In [12]:
simple_train_dtm = vect.transform(simple_train)
simple_train_dtm

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [13]:
# convert sparse matrix to a dense matrix
simple_train_dtm.toarray()

array([[0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 2, 0, 0]], dtype=int64)

In [15]:
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_train_dtm.toarray(), columns=vect.get_feature_names())

cab  call  me  please  tonight  you
0    0     1   0       0        1    1
1    1     1   1       0        0    0
2    0     1   1       2        0    0

In [16]:
# check the type of the document-term matrix
type(simple_train_dtm)

scipy.sparse.csr.csr_matrix

In [17]:
# examine the sparse matrix contents
print(simple_train_dtm)

  (0, 1)	1
  (0, 4)	1
  (0, 5)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	2


In [21]:
f = open("data.txt")

In [24]:
data = f.readlines()

In [40]:
newData = []
for line in data:
    newData = newData+line.split()
newData

['WeServeEveryone',
 'Clinic',
 '1111',
 'First',
 'Street',
 'California',
 '111-111-11111',
 'Fax:',
 '111-111-1111',
 'Chart',
 'Summary',
 'Monica',
 'Latte',
 'Home:',
 '444-444-4444',
 'Female',
 'DOB:',
 '04/04/1950',
 '0000-44444',
 'Ins:',
 'Commercial',
 'xxxxx',
 'Patient',
 'Information',
 'Name:',
 'Monica',
 'Latte',
 'Home',
 'Phone:',
 '444-444-4444',
 'Address:',
 '4444',
 'Coffee',
 'Ave',
 'Chocolate,',
 'California',
 'Office',
 'Phone:',
 'Patient',
 'ID:',
 '0000-44444',
 'Fax:',
 'Birth',
 'Date:',
 '04/04/1950',
 'Status:',
 'Active',
 'Gender:',
 'Female',
 'Marital',
 'Status:',
 'Divorced',
 'Contact',
 'By:',
 'Phone',
 'Race:',
 'Black',
 'Soc',
 'Sec',
 'No:',
 '444-444-4444',
 'Language:',
 'English',
 'Resp',
 'Prov:',
 'Carl',
 'Savem',
 'MRN:',
 'MR-111-1111',
 'Referred',
 'by:',
 'Emp.',
 'Status:',
 'Full-time',
 'Email:',
 'Sens',
 'Chart:',
 'No',
 'Home',
 'LOC:WeServeEveryone',
 'External',
 'ID:',
 'MR-111-1111',
 'Problems',
 'DIABETES',
 'MEL

In [41]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
vect.fit(newData)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [42]:
vect.get_feature_names()

['0000',
 '03',
 '03chem',
 '04',
 '08',
 '10',
 '100',
 '101',
 '107',
 '109',
 '110',
 '111',
 '1111',
 '11111',
 '120',
 '125',
 '135',
 '136',
 '140',
 '142',
 '145',
 '158',
 '16',
 '18',
 '1950',
 '20',
 '200',
 '2010',
 '2011',
 '210',
 '220',
 '23',
 '236',
 '24',
 '25',
 '250',
 '27',
 '29',
 '30',
 '31',
 '35',
 '36',
 '40',
 '401',
 '444',
 '4444',
 '44444',
 '600',
 '64',
 '70',
 '72',
 '90',
 '96',
 '98',
 'abdominal',
 'ac',
 'acid',
 'active',
 'acute',
 'address',
 'adenopathy',
 'adverse',
 'agitation',
 'alk',
 'allergic',
 'allergies',
 'amnesia',
 'and',
 'anemia',
 'annual',
 'anxiety',
 'appearance',
 'are',
 'ast',
 'at',
 'auscultation',
 'ave',
 'back',
 'behaviors',
 'benign',
 'bg',
 'bili',
 'birth',
 'black',
 'bleeding',
 'blood',
 'blurred',
 'blurring',
 'booster',
 'bp',
 'breakfast',
 'breast',
 'bruising',
 'bruits',
 'bun',
 'by',
 'calcium',
 'california',
 'callouses',
 'cardiovascular',
 'care',
 'carl',
 'change',
 'changes',
 'chart',
 'chest',


In [43]:
simple_train_dtm = vect.transform(data)
simple_train_dtm

<197x451 sparse matrix of type '<class 'numpy.int64'>'
	with 777 stored elements in Compressed Sparse Row format>

In [44]:
# convert sparse matrix to a dense matrix
simple_train_dtm.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [45]:
pd.DataFrame(simple_train_dtm.toarray(), columns=vect.get_feature_names())

0000  03  03chem  04  08  10  100  101  107  109  ...    weight  well  \
0       0   0       0   0   0   0    0    0    0    0  ...         0     0   
1       0   0       0   0   0   0    0    0    0    0  ...         0     0   
2       0   0       0   0   0   0    0    0    0    0  ...         0     0   
3       0   0       0   0   0   0    0    0    0    0  ...         0     0   
4       0   0       0   0   0   0    0    0    0    0  ...         0     0   
5       0   0       0   0   0   0    0    0    0    0  ...         0     0   
6       1   0       0   2   0   0    0    0    0    0  ...         0     0   
7       0   0       0   0   0   0    0    0    0    0  ...         0     0   
8       0   0       0   0   0   0    0    0    0    0  ...         0     0   
9       0   0       0   0   0   0    0    0    0    0  ...         0     0   
10      0   0       0   0   0   0    0    0    0    0  ...         0     0   
11      0   0       0   0   0   0    0    0    0    0  ...         0     0   
12      0   0       0   0   0   0    0    0    0    0  ...         0     0   
13      1   0       0   0   0   0    0    0    0    0  ...         0     0   
14      0   0       0   2   0   0    0    0    0    0  ...         0     0   
15      0   0       0   0   0   0    0    0    0    0  ...         0     0   
16      0   0       0   0   0   0    0    0    0    0  ...         0     0   
17      0   0       0   0   0   0    0    0    0    0  ...         0     0   
18      0   0       0   0   0   0    0    0    0    0  ...         0     0   
19      0   0       0   0   0   0    0    0    0    0  ...         0     0   
20      0   0       0   0   0   0    0    0    0    0  ...         0     0   
21      0   0       0   0   0   0    0    0    0    0  ...         0     0   
22      0   0       0   0   0   0    0    0    0    0  ...         0     0   
23      0   0       0   0   0   0    0    0    0    0  ...         0     0   
24      0   0       0   0   0   0    0    0    0    0  ...         0     0   
25      0   0       0   0   0   0    0    0    0    0  ...         0     0   
26      0   0       0   0   0   0    0    0    0    0  ...         0     0   
27      0   0       0   0   0   0    0    0    0    0  ...         0     0   
28      0   0       0   0   1   0    0    0    0    0  ...         0     0   
29      0   0       0   0   0   0    0    0    0    0  ...         0     0   
..    ...  ..     ...  ..  ..  ..  ...  ...  ...  ...  ...       ...   ...   
167     0   0       0   0   0   0    0    0    0    0  ...         0     0   
168     0   0       0   0   0   0    0    0    0    0  ...         0     0   
169     0   0       0   0   0   0    0    0    0    0  ...         0     0   
170     1   0       0   2   0   0    0    0    0    0  ...         0     0   
171     0   0       0   0   0   0    0    0    0    0  ...         0     0   
172     0   1       0   0   0   0    0    0    0    0  ...         0     0   
173     0   0       0   0   0   0    0    0    0    0  ...         0     0   
174     0   0       0   0   0   0    0    0    0    0  ...         1     0   
175     0   0       0   0   0   0    0    0    0    0  ...         0     0   
176     0   0       0   0   0   0    0    0    0    0  ...         0     0   
177     0   0       0   0   0   0    0    0    0    0  ...         0     0   
178     0   0       0   0   0   0    0    0    0    0  ...         0     0   
179     0   0       0   0   0   0    0    0    0    0  ...         0     0   
180     0   0       0   0   0   0    0    0    0    0  ...         0     0   
181     0   0       0   0   0   0    0    0    0    0  ...         0     0   
182     0   0       0   0   0   0    0    0    0    0  ...         0     0   
183     0   0       0   0   0   0    0    0    0    0  ...         0     0   
184     0   0       0   0   0   0    0    0    0    0  ...         0     0   
185     0   0       0   0   0   0    0    0    0    0  ...         0     0   
186     0   0       0   0  

In [38]:
print(simple_train_dtm)

  (0, 112)	1
  (0, 443)	1
  (1, 12)	1
  (1, 97)	1
  (1, 185)	1
  (1, 393)	1
  (2, 11)	4
  (2, 12)	1
  (2, 13)	1
  (2, 104)	1
  (2, 181)	1
  (2, 398)	1
  (3, 251)	1
  (3, 286)	1
  (5, 44)	2
  (5, 45)	1
  (5, 218)	1
  (6, 0)	1
  (6, 3)	2
  (6, 24)	1
  (6, 46)	1
  (6, 118)	1
  (6, 157)	1
  (6, 183)	1
  (6, 237)	1
  :	:
  (185, 15)	1
  (185, 80)	1
  (185, 156)	1
  (185, 279)	1
  (185, 353)	1
  (186, 133)	1
  (187, 168)	1
  (188, 321)	1
  (188, 385)	1
  (189, 91)	1
  (189, 175)	1
  (190, 269)	1
  (191, 212)	1
  (191, 298)	1
  (192, 186)	1
  (192, 435)	1
  (193, 334)	1
  (194, 88)	1
  (194, 283)	1
  (194, 408)	1
  (195, 175)	1
  (195, 188)	1
  (196, 121)	1
  (196, 175)	1
  (196, 178)	1


In [46]:
simple_test = ["i go to clinic"]

In [47]:
simple_test_dtm = vect.transform(simple_test)
simple_test_dtm.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [48]:
pd.DataFrame(simple_test_dtm.toarray(), columns=vect.get_feature_names())

0000  03  03chem  04  08  10  100  101  107  109  ...    weight  well  \
0     0   0       0   0   0   0    0    0    0    0  ...         0     0   

   weserveeveryone  wheezing  will  with  wnl  work  wt  xxxxx  
0                0         0     0     0    0     0   0      0  

[1 rows x 451 columns]

In [49]:

# alternative: read file into pandas from a URL
url = 'https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv'
sms = pd.read_table(url, header=None, names=['label', 'message'])

In [50]:

# examine the shape
sms.shape

(5572, 2)

In [51]:
# examine the first 10 rows
sms.head(10)

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...